name: Docker Image CI for GHCR

on: 
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm ci
      - name: run the unit tests
        run: npm test
      - name: Build and push the image
        run: |
          docker login --username remehrinpersonal --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/remehrinpersonal/arithmetic-service:1 --file Dockerfile .
          docker push ghcr.io/remehrinpersonal/arithmetic-service:1
      - name: Publish the image to azure container registry
        run: |
          docker login --username practicum16cra --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicum16cra.azurecr.io
          docker tag ghcr.io/remehrinpersonal/arithmetic-service:1 practicum16cra.azurecr.io/arithmetic-service:1
          docker push practicum16cra.azurecr.io/arithmetic-service:1